# Configuration parameters for the bot

telegram_api:

  # Get the bot token from '@botfather'
  # https://www.siteguarding.com/en/how-to-get-telegram-bot-api-token
  bot_token:

  # Chat id for the dev (send errors, info, etc.)
  dev_chat_id:

  # List of user's chat id with access to the power on/off functions,
  # leave empty for no restriction (not recommended)
  allowed_chats:

host_pc:
  local_ip:  # Set up a fixed local ip first
  username:
  grub_windows_entry: 1  # Second entry

pin_wiring:
  # GPIO number of the pins were the positive of the relay
  # For reference https://es.pinout.xyz/pinout/io_pi_zero
  power_pin: 21  # Pin 40 on board
  reset_pin: 20  # Pin 38 on board
